# READ-ONLY: Use 'exo' CLI to modify this file.
# Task List

[[tasks]]
id = "First Step::29.1"
title = "Plugin Mechanism: Formal system for custom services"
status = "pending"

[[tasks]]
id = "First Step::29.2"
title = "Packaging: Support locald package command"
status = "pending"

[[tasks]]
id = "First Step::29.3"
title = "Distributions: Allow flavored binaries/configs"
status = "pending"

