[package]
name = "locald-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
locald-core = { version = "0.1.0", path = "../locald-core" }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
