[package]
name = "oci-example"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
locald-oci = { path = "../../locald-oci" }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"
