[package]
name = "rust-extractor"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.100"
flate2 = "1.1.5"
oci-distribution = "0.11.0"
tar = "0.4.44"
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
